name: Release

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Release Branch Name'
        default: ''
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch_name }}

      - name: Set up Apache Maven Central
        uses: actions/setup-java@v3
        with: # running setup-java again overwrites the settings.xml
          distribution: 'temurin'
          java-version: '11'
          java-package: jdk
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: OSSH_USERNAME # env variable for username in deploy (1)
          server-password: OSSH_PASSWORD # env variable for token in deploy (2)

      - name: Perform Release
        run: |
          mvn --batch-mode --no-transfer-progress deploy -P release -DskipTests -Dgpg.signer=bc
        env:
          OSSH_USERNAME: ${{ secrets.OSSH_USERNAME }}
          OSSH_PASSWORD: ${{ secrets.OSSH_PASSWORD }}
          OSSH_GPG_PASSPHRASE: ${{ secrets.OSSH_GPG_PASSPHRASE }}
          MAVEN_GPG_KEY: ${{ secrets.OSSH_GPG_PRIVATE_KEY }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSH_GPG_PASSPHRASE }}
